import Head from 'next/head'
import Image from 'next/image'

import Title from '../components/Title'
import SubTitle from '../components/SubTitle'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Login|SDL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       
      </main>
    </div>
  )
}
